apiVersion: v1
kind: ConfigMap
metadata:
  name: phl-sno1-extra-manifests
  namespace: phl-sno1
data:
  99-phl-sno1-kargs-mc.yaml: |
    apiVersion: machineconfiguration.openshift.io/v1
    kind: MachineConfig
    metadata:
      name: 99-master-phl-sno1-kargs
      labels:
        machineconfiguration.openshift.io/role: master
    spec:
      kernelArguments:
        - "loglevel=4"
