apiVersion: v1
kind: ConfigMap
metadata:
  name: rhoai-extra-manifests
  namespace: rhoai
data:
  99-rhoai-kargs-mc.yaml: |
    apiVersion: machineconfiguration.openshift.io/v1
    kind: MachineConfig
    metadata:
      name: 99-master-rhoai-kargs
      labels:
        machineconfiguration.openshift.io/role: master
    spec:
      kernelArguments:
        - "loglevel=4"
