---
apiVersion: siteconfig.open-cluster-management.io/v1alpha1
kind: ClusterInstance
metadata:
  name: "phl-sno1"
  namespace: "phl-sno1"
spec:
  baseDomain: "ocp-poc-demo.com"
  clusterImageSetNameRef: "img4.20.8-x86-64-appsub"
  clusterName: "phl-sno1"
  clusterNetwork:
    - cidr: "10.128.0.0/14"
      hostPrefix: 23
  cpuPartitioningMode: AllNodes
  extraLabels:
    ManagedCluster:
      siteName: "phl"
      group-du-sno: ""
      logicalGroup: "active"
      common-418-disconnected: "false"
      common-418-resource-usage-test: ""
  holdInstallation: false
  installConfigOverrides: |
    {
      "capabilities": {
        "baselineCapabilitySet": "None",
        "additionalEnabledCapabilities": [
          "NodeTuning",
          "OperatorLifecycleManager",
          "Ingress"
        ]
      }
    }
  machineNetwork:
    - cidr: "192.168.4.0/24"
  networkType: "OVNKubernetes"
  pullSecretRef:
    name: "assisted-deployment-pull-secret"
  serviceNetwork:
    - cidr: "172.30.0.0/16"
  sshPublicKey: "c3NoLXJzYSBBQUFBQjNOemFDMXljMkVBQUFBREFRQUJBQUFCZ1FEWTRGRlhPcjN5NTJneURWR2VadnRmK0xlM05Ma2xsc0dxSmZLTFdRT3BIcEw3QUZsaWJLL1lCbFpNRDV5VC8vWlZKMWcrQXJlU1pwY2JuZ3ZjVkZkTWhTTDhlRlNIR0RBVDFhWklSVmRQblEvM2VOckxzTGpsZGlSK0hUMTkxUUVIbDNESFkwWnlUMzdybDMwQ1E1eGlVZDcvNVplbWlBcnlwbnhqZWxzYVlJRW5UNVVjUkRPQWszQ0RQYkY4TTBnTk53TkFxS21SR05LY0ptVGdTU0xqSkdEYmx4TkdNazVUSWwyMXl4TlpxSnFEZFFnajRzOWNwME9NNVpQZzFaRTlzeUtTcWcvUGtOY09aNVBWekZyT3BWc1ZKVGlTblRQbFU1Ym1xYnJ3bkgzaWoyUWR0U0JoNGZ6bmNoYVk2ejM4dVQ4RUJ6WHljdXZhSUxMVlZsMlFhL21JVGp1ak1WaWNuRFlwaWxVZW9EbmQ2L1pSNlFaZktuQ0J6L1Q0TVEyNHdDMlRseFhxdE5TcGFJYkFPc05vdmJPdkRtdDVpREQxZ3NSR1hmeXJMakRBelVKS0hPS1dHa0xiY29sR2pTZW1xenZmZURVLzdpQTkwelVoR09SbWJhd1FjUWVSSEV3eklYenBMK1NieTNudHJ4NGEvS0k1U1R3OXJDVEFzUEU9IGtlaXRoQHZwbi1ob3BwZXIuY2FsbGlnYW4ubmFtZQo="
  templateRefs:
    - name: ai-cluster-templates-v1
      namespace: open-cluster-management
  nodes:
    - automatedCleaningMode: "disabled"
      bmcAddress: "redfish-virtualmedia+http://192.168.4.152:8000/redfish/v1/Systems/d5acc567-ce36-4e7b-bbac-a49719e13c51"
      bmcCredentialsName:
        name: "bmc-phl-sno1-host1"
      bootMACAddress: "52:54:00:fe:79:03"
      bootMode: "UEFI"
      hostName: "phl-sno1-host1"
      nodeNetwork:
        interfaces:
          - name: "eno1"
            macAddress: "52:54:00:fe:79:03"
        config:
          interfaces:
            - name: eno1
              type: ethernet
              state: up
              ipv4:
                address:
                  - ip: 192.168.4.223
                    prefix-length: 24
                enabled: true
                dhcp: false
              ipv6:
                enabled: false
          dns-resolver:
            config:
              server:
                - 8.8.8.8
                - 8.8.4.4
          routes:
            config:
              - destination: '0.0.0.0/0'
                next-hop-address: '192.168.4.1'
                next-hop-interface: eno1
      role: "master"
      templateRefs:
        - name: ai-node-templates-v1
          namespace: open-cluster-management
