---
apiVersion: siteconfig.open-cluster-management.io/v1alpha1
kind: ClusterInstance
metadata:
  name: "rhoai"
  namespace: "rhoai"
spec:
  baseDomain: "ocp-poc-demo.com"
  clusterImageSetNameRef: "img4.20.8-x86-64-appsub"
  clusterName: "phl-sno1"
  clusterNetwork:
    - cidr: "10.128.0.0/14"
      hostPrefix: 23
  extraManifestsRefs:
    - name: rhoai-extra-manifests
  extraLabels:
    ManagedCluster:
      siteName: "phl"
      group-du-sno: ""
      logicalGroup: "active"
      common-418-disconnected: "false"
      common-418-resource-usage-test: ""
  holdInstallation: false
  machineNetwork:
    - cidr: "192.168.4.0/24"
  networkType: "OVNKubernetes"
  pullSecretRef:
    name: "assisted-deployment-pull-secret"
  serviceNetwork:
    - cidr: "172.30.0.0/16"
  sshPublicKey: "ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQDY4FFXOr3y52gyDVGeZvtf+Le3NLkllsGqJfKLWQOpHpL7AFlibK/YBlZMD5yT//ZVJ1g+AreSZpcbngvcVFdMhSL8eFSHGDAT1aZIRVdPnQ/3eNrLsLjldiR+HT191QEHl3DHY0ZyT37rl30CQ5xiUd7/5ZemiArypnxjelsaYIEnT5UcRDOAk3CDPbF8M0gNNwNAqKmRGNKcJmTgSSLjJGDblxNGMk5TIl21yxNZqJqDdQgj4s9cp0OM5ZPg1ZE9syKSqg/PkNcOZ5PVzFrOpVsVJTiSnTPlU5bmqbrwnH3ij2QdtSBh4fznchaY6z38uT8EBzXycuvaILLVVl2Qa/mITjujMVicnDYpilUeoDnd6/ZR6QZfKnCBz/T4MQ24wC2TlxXqtNSpaIbAOsNovbOvDmt5iDD1gsRGXfyrLjDAzUJKHOKWGkLbcolGjSemqzvfeDU/7iA90zUhGORmbawQcQeRHEwzIXzpL+Sby3ntrx4a/KI5STw9rCTAsPE= keith@vpn-hopper.calligan.name" 
  templateRefs:
    - name: ai-cluster-templates-v1
      namespace: open-cluster-management
  nodes:
    - automatedCleaningMode: "disabled"
      bmcAddress: "redfish-virtualmedia+http://192.168.4.153:8000/redfish/v1/Systems/6ffbce0c-42de-4537-8079-633eca1962e9"
      bmcCredentialsName:
        name: "bmc-rhoai"
      bootMACAddress: "52:54:00:18:10:5b"
      bootMode: "UEFI"
      hostName: "rhoai-host1"
      nodeNetwork:
        interfaces:
          - name: "eno1"
            macAddress: "52:54:00:18:10:5b"
        config:
          interfaces:
            - name: eno1
              type: ethernet
              state: up
              ipv4:
                address:
                  - ip: 192.168.4.224
                    prefix-length: 24
                enabled: true
                dhcp: false
              ipv6:
                enabled: false
          dns-resolver:
            config:
              server:
                - 8.8.8.8
                - 8.8.4.4
          routes:
            config:
              - destination: '0.0.0.0/0'
                next-hop-address: '192.168.4.1'
                next-hop-interface: eno1
      role: "master"
      templateRefs:
        - name: ai-node-templates-v1
          namespace: open-cluster-management
